# Generated by Django 4.1.2 on 2022-11-27 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='acoustic',
        ),
        migrations.RemoveField(
            model_name='log',
            name='geophone',
        ),
        migrations.RemoveField(
            model_name='log',
            name='snapshot',
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=32)),
                ('picture', models.ImageField(upload_to='snapshots')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='erp.log')),
            ],
        ),
        migrations.CreateModel(
            name='Geophone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('logfile', models.FileField(upload_to='geophone_logfiles')),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geophone_data', to='erp.log')),
            ],
        ),
        migrations.CreateModel(
            name='Acoustic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('logfile', models.FileField(upload_to='acoustic_logfiles')),
                ('recording', models.FileField(upload_to='acoustic_recordings')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoustic_data', to='erp.log')),
            ],
        ),
    ]
