# Generated by Django 4.1.2 on 2022-11-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_rename_log_acoustic_log_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acoustic',
            new_name='AcousticLog',
        ),
        migrations.RenameModel(
            old_name='Geophone',
            new_name='GeophoneLog',
        ),
        migrations.RenameModel(
            old_name='Log',
            new_name='LogGroup',
        ),
        migrations.RenameModel(
            old_name='Snapshot',
            new_name='SnapshotLog',
        ),
    ]
